on:
  workflow_dispatch:
env:
  SYNC_GIT_REMOTE: git@gitlab.com:taka-ios-team/test-app.git
  SYNC_GIT_REMOTE_NAME: syncserver 


jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_SYNC_GIT_PRIVATE_KEY }}

    - name: Add Remote Repository
      run: git remote add $SYNC_GIT_REMOTE_NAME $SYNC_GIT_REMOTE

    - name: Get latest from sync other
      run: |
        git fetch $SYNC_GIT_REMOTE_NAME 
        for remote in `git branch -r`; do git branch --track ${remote#$SYNC_GIT_REMOTE_NAME/} $remote; done  
        ./.github/workflows/pull-all-remote-branches.bash	

    - name: push latest to sync other 
      run: git push --all $SYNC_GIT_REMOTE_NAME

    - name: Push Changes to this Repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin main
