name: Triggerable pages deployment

on:
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch:
    inputs:
      website_artifact_name:
        type: string
      website_artifact_repo:
        type: string
      website_artifact_workflow_run_id:
        type: string


    
jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#        with:
#        ref: ${{ github.event.inputs.sha }}

  deploy-external:

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: "${{ steps.pages_setup.outputs.page_url }}"

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        id: pages_setup
        uses: actions/configure-pages@v5
      
      - uses: actions/download-artifact@v4
        with:
          name:  ${{ github.event.inputs.website_artifact_name }}  
          github-token: ${{ secrets.APP_SOURCE_REPO_PAT }} # token with actions:read permissions on target repo
          repository: ${{ github.event.inputs.website_artifact_repo }}
          run-id: ${{ github.event.inputs.website_artifact_workflow_run_id }}
          path: "./artifact"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.website_artifact_name }}  
          path: "./artifact"
          retention-days: 1
          if-no-files-found: error


 #    - name: Upload source and icon to Source Website
 #      uses: actions/upload-pages-artifact@v3
 #      with:
 #        # location of the coverage artifacts
 #        path: "./artifact"
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
      