on:
  workflow_dispatch:
env:
  SYNC_GIT_REMOTE: git@gitlab.com:taka-ios-team/test-app.git
  SYNC_GIT_REMOTE_NAME: syncserver 

permissions:
  contents: write

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_SYNC_GIT_PRIVATE_KEY }}

    - name: Add Remote Host to Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

    - name: Add Remote Repository
      run: git remote add $SYNC_GIT_REMOTE_NAME $SYNC_GIT_REMOTE

    - name: fetch all remotes
      run: |
        git fetch -all 

    - name: create branches
      run: |
        for remote in `git branch -r`; do git branch --track ${remote#$SYNC_GIT_REMOTE_NAME/} $remote; done  
    
    - name: Get 
      run: |
        ./.github/workflows/pull-all-remote-branches.bash	

    - name: push latest to sync other 
      run: git push --all $SYNC_GIT_REMOTE_NAME

    - name: Push Changes to this Repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push --all origin
